//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASU_Proxy.ServiceEtran {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEtran.SysCISS")]
    public interface SysCISS {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (nsCISS) сообщения SendBlockRequest не соответствует значению по умолчанию (http://tempuri.org/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:nsCISS", ReplyAction="*")]
        ASU_Proxy.ServiceEtran.SendBlockResponse SendBlock(ASU_Proxy.ServiceEtran.SendBlockRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен упаковщика (nsCISS) сообщения GetBlockRequest не соответствует значению по умолчанию (http://tempuri.org/).
        [System.ServiceModel.OperationContractAttribute(Action="urn:nsCISS", ReplyAction="*")]
        ASU_Proxy.ServiceEtran.GetBlockResponse GetBlock(ASU_Proxy.ServiceEtran.GetBlockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBlock", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class SendBlockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Text;
        
        public SendBlockRequest() {
        }
        
        public SendBlockRequest(string Text) {
            this.Text = Text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendBlockResponse", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class SendBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public SendBlockResponse() {
        }
        
        public SendBlockResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBlock", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class GetBlockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string text;
        
        public GetBlockRequest() {
        }
        
        public GetBlockRequest(string login, string password, string text) {
            this.login = login;
            this.password = password;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBlockResponse", WrapperNamespace="nsCISS", IsWrapped=true)]
    public partial class GetBlockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string text;
        
        public GetBlockResponse() {
        }
        
        public GetBlockResponse(bool @return, string text) {
            this.@return = @return;
            this.text = text;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SysCISSChannel : ASU_Proxy.ServiceEtran.SysCISS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SysCISSClient : System.ServiceModel.ClientBase<ASU_Proxy.ServiceEtran.SysCISS>, ASU_Proxy.ServiceEtran.SysCISS {
        
        public SysCISSClient() {
        }
        
        public SysCISSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SysCISSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysCISSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysCISSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASU_Proxy.ServiceEtran.SendBlockResponse ASU_Proxy.ServiceEtran.SysCISS.SendBlock(ASU_Proxy.ServiceEtran.SendBlockRequest request) {
            return base.Channel.SendBlock(request);
        }
        
        public bool SendBlock(string Text) {
            ASU_Proxy.ServiceEtran.SendBlockRequest inValue = new ASU_Proxy.ServiceEtran.SendBlockRequest();
            inValue.Text = Text;
            ASU_Proxy.ServiceEtran.SendBlockResponse retVal = ((ASU_Proxy.ServiceEtran.SysCISS)(this)).SendBlock(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASU_Proxy.ServiceEtran.GetBlockResponse ASU_Proxy.ServiceEtran.SysCISS.GetBlock(ASU_Proxy.ServiceEtran.GetBlockRequest request) {
            return base.Channel.GetBlock(request);
        }
        
        public bool GetBlock(string login, string password, ref string text) {
            ASU_Proxy.ServiceEtran.GetBlockRequest inValue = new ASU_Proxy.ServiceEtran.GetBlockRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.text = text;
            ASU_Proxy.ServiceEtran.GetBlockResponse retVal = ((ASU_Proxy.ServiceEtran.SysCISS)(this)).GetBlock(inValue);
            text = retVal.text;
            return retVal.@return;
        }
    }
}
